const bodyParser = require('body-parser')
const express = require('express')
const app = express()
const path = require('path')
require('dotenv').config()
app.use(express.static(path.join(__dirname, 'public')))
app.use(express.static(path.join(__dirname, 'node_modules')))
